public enum Screens 
{
    HomeScreen,
    LineupScreen,
    PitchFinderScreen,
    AvailabilityPlannerScreen,
    BookingBuilderScreen,
    BookingConfirmScreen,
    BookingDetailsScreen,
    MyBookingScreen,
    WalletScreen,
    ProfileScreen,
    PlayersManagementScreen,
    MatchCenterScreen,
    FinishBookingScreen,
    NotificationsScreen,
    //Onboarding
    LoadingScreen,
    OnboradingScreen
}
